
import { GoogleGenAI, Type, GenerateContentResponse } from "@google/genai";

const getAIClient = () => {
  return new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
};

export async function generateDesignVariant(baseImageBase64: string, stylePrompt: string): Promise<string> {
  const ai = getAIClient();
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: baseImageBase64.split(',')[1],
            mimeType: 'image/png',
          },
        },
        {
          text: `Please transform this interior space. ${stylePrompt}. Maintain the basic architecture and room layout, but completely change the furniture, decor, flooring, and wall treatments to match the style described.`,
        },
      ],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }
  throw new Error("No image generated by the model.");
}

export async function editDesignWithPrompt(baseImageBase64: string, editPrompt: string): Promise<string> {
  const ai = getAIClient();
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: baseImageBase64.split(',')[1],
            mimeType: 'image/png',
          },
        },
        {
          text: `Take this room design and apply the following change: ${editPrompt}. Maintain everything else as is.`,
        },
      ],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }
  throw new Error("No image generated for edit.");
}

export async function chatAboutDesign(
  message: string, 
  history: {role: 'user' | 'assistant', content: string}[],
  currentImageBase64?: string
): Promise<{ text: string; links?: string[] }> {
  const ai = getAIClient();
  
  const contents: any = history.map(h => ({
    role: h.role === 'user' ? 'user' : 'model',
    parts: [{ text: h.content }]
  }));

  const userParts: any[] = [{ text: message }];
  if (currentImageBase64) {
    userParts.push({
      inlineData: {
        data: currentImageBase64.split(',')[1],
        mimeType: 'image/png'
      }
    });
  }

  contents.push({ role: 'user', parts: userParts });

  const response = await ai.models.generateContent({
    model: 'gemini-3-pro-preview',
    contents: contents,
    config: {
      systemInstruction: `You are an expert AI Interior Design Consultant named Lumina. 
      You help users refine their room designs. If the user asks for shoppable links or where to buy items, 
      provide helpful descriptions and search terms. 
      When analyzing images, focus on lighting, texture, spatial layout, and color harmony. 
      Always be professional, encouraging, and sophisticated.`,
      tools: [{ googleSearch: {} }]
    }
  });

  const text = response.text || "I'm sorry, I couldn't generate a response.";
  const groundingChunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks;
  const links = groundingChunks?.map((chunk: any) => chunk.web?.uri).filter(Boolean);

  return { text, links };
}
